### PR TITLE
Adding SNX and sUSD to token list

### PR DESCRIPTION
**Pull request by degenspartan**
Allows SNX and sUSD to be discoverable without manually searching for the address.

### CODE REVIEW

**Comment by degenspartan** [comment]
Changed the inserted addresses to be alphabetical instead of at the end.

**Comment by degenspartan** [comment]
Hi @ChristophSiegenthaler is there any issue to merge this PR?

**Comment by ChristophSiegenthaler** [comment]
Well we're currently pulling the token logos from https://raw.githubusercontent.com/TrustWallet/tokens/master/tokens and this doesn't work for SNX and SUSD. Haven't had time to look into this too deeply yet.

**Comment by hav-noms** [comment]
@ChristophSiegenthaler the logos won't be there as these contract addresses are direct whereas we usually point publicly to our proxy contracts which are 
SNX
https://github.com/TrustWallet/tokens/blob/master/tokens/0xc011a72400e58ecd99ee497cf89e3775d4bd732f.png

and sUSD 
https://github.com/TrustWallet/tokens/blob/master/tokens/0x57ab1e02fee23774580c119740129eac7081e9d3.png

Proxy.sUSD           │ 0x57Ab1E02fEE23774580C119740129eAC7081e9D3 
Synth.sUSD           │ 0x0cbe2df57ca9191b64a7af3baa3f946fa7df2f25 

Proxy.Synthetix     │ 0xC011A72400E58ecD99Ee497CF89E3775d4bd732F 
Synthetix               │ 0x3772f9716Cf6D7a09edE3587738AA2af5577483a

**Comment by hav-noms** [comment]
@ChristophSiegenthaler do you want me to push these logos with the underlying contract address somewhere?

**Comment by ChristophSiegenthaler** [comment]
Merged. For now without logo.

**Comment by degenspartan** [comment]
Thanks Christoph, I appreciate the work you're doing with this fork!

**Pull request merged**
